# Generated by Django 5.1.6 on 2025-02-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_alumno', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('nombre_padre', models.CharField(max_length=100)),
                ('nombre_madre', models.CharField(max_length=100)),
                ('grado', models.CharField(max_length=50)),
                ('seccion', models.CharField(max_length=10)),
                ('fecha_ingreso', models.DateField()),
                ('test_field', models.CharField(default='temp', max_length=10)),
            ],
            options={
                'db_table': 'tbl_alumno',
            },
        ),
    ]
