# Generated by Django 5.1.6 on 2025-02-08 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='test_field',
        ),
    ]
